name: Product Api Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/yudbox/nest_projects/nest-product-card-api/nest-product-card-api
          username: ${{ secrets.DOCKER_USERNAME_PRODUCT }}
          password: ${{ secrets.DOCKER_PASSWORD_PRODUCT }}
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
